name: API Test Challenge CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Cucumber tests
        run: npm test
        
      - name: Generate HTML Report
        if: always()
        run: npm run report

      - name: Upload Cucumber JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: cucumber_report.json

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: cucumber_report.html

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            cucumber_report.json
            cucumber_report.html